# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 890760e50d9c641295c0432b04372be6cf33117c0584b4623343c7bdbaa0278956e0be97859f7e3d40aabbba0c3c1bd830e8060c60601ec74e68bf6d11668557

test:
  secret_key_base: bf98a254068139ae2624fc1804d1cc7b161f31f08e630a8f3ceaacca92d7e2ac2407b1ad7485f857ad2145df6917efb1077c7beb90353abeb081103bed41462c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
