# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Workspace.create!(host_id:'12', name:'Meltwater Incubator',country:'Ghana' ,location:'Accra',description: 'Welcome to Meltwater. We are more than just an office space; we are a dynamic coworking community of startup founders, freelancers, entrepreneurs and small teams who are working to build dreams.' ,seats:'5' ,price: '40'  , picture: Rails.root.join('/home/worlanyo/Documents/capstone/ForkedCapstone/dijispace/public/uploads/workspace/picture/2/meeting-modern-room-conference-159805.jpeg').open ) 
Workspace.create!(host_id:'13', name:'Conference Room',country:'Ghana' ,location:'Osu',description: 'Welcome to Workshed. We are more than just an office space; we are a dynamic coworking community of startup founders, freelancers, entrepreneurs and small teams who are working to build dreams.' ,seats:'5' ,price: '40'  , picture: Rails.root.join('/home/worlanyo/Documents/capstone/ForkedCapstone/dijispace/public/uploads/workspace/picture/2/meeting-modern-room-conference-159805.jpeg').open ) 
Workspace.create!(host_id:'13', name:'Meeting Room',country:'Ghana' ,location:'Osu',description: 'Welcome to Workshed. We are more than just an office space; we are a dynamic coworking community of startup founders, freelancers, entrepreneurs and small teams who are working to build dreams.' ,seats:'5' ,price: '40'  , picture: Rails.root.join('/home/worlanyo/Documents/capstone/ForkedCapstone/dijispace/public/uploads/workspace/picture/2/meeting-modern-room-conference-159805.jpeg').open ) 
Workspace.create!(host_id:'13', name:'Office Space',country:'Ghana' ,location:'Osu',description: 'Welcome to Workshed. We are more than just an office space; we are a dynamic coworking community of startup founders, freelancers, entrepreneurs and small teams who are working to build dreams.' ,seats:'5' ,price: '40'  , picture: Rails.root.join('/home/worlanyo/Documents/capstone/ForkedCapstone/dijispace/public/uploads/workspace/picture/2/meeting-modern-room-conference-159805.jpeg').open ) 
Workspace.create!(host_id:'12', name:'Impact Hub',country:'Ghana' ,location:'Accra',description: 'Welcome to Impact Hub. We are more than just an office space; we are a dynamic coworking community of startup founders, freelancers, entrepreneurs and small teams who are working to build dreams.' ,seats:'5' ,price: '40'  , picture: Rails.root.join('/home/worlanyo/Documents/capstone/ForkedCapstone/dijispace/public/uploads/workspace/picture/2/meeting-modern-room-conference-159805.jpeg').open ) 
Workspace.create!(host_id:'12', name:'Ispace Hub',country:'Ghana' ,location:'Accra',description: 'Welcome to Ispace. We are more than just an office space; we are a dynamic coworking community of startup founders, freelancers, entrepreneurs and small teams who are working to build dreams.' ,seats:'5' ,price: '40'  , picture: Rails.root.join('/home/worlanyo/Documents/capstone/ForkedCapstone/dijispace/public/uploads/workspace/picture/2/meeting-modern-room-conference-159805.jpeg').open ) 